package com.sliidepoc.ui.themes

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF29BCF2)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF97f7b8)
val md_theme_light_onPrimaryContainer = Color(0xFFffffff)
val md_theme_light_secondary = Color(0xFF4f6354)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF384b3d)
val md_theme_light_onSecondaryContainer = Color(0xFFd2e8d5)
val md_theme_light_tertiary = Color(0xFF3a646f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbfeaf7)
val md_theme_light_onTertiaryContainer = Color(0xFF001f27)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf7)
val md_theme_light_onBackground = Color(0xFF191c1a)
val md_theme_light_surface = Color(0xFFfbfdf7)
val md_theme_light_onSurface = Color(0xFF191c1a)
val md_theme_light_surfaceVariant = Color(0xFFdce5db)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFF191c1a)
val md_theme_light_inverseSurface = Color(0xFF2e312e)

val md_theme_dark_primary = Color(0xFF29BCF2)
val md_theme_dark_onPrimary = Color(0xFFffffff)
val md_theme_dark_primaryContainer = Color(0xFF97f7b8)
val md_theme_dark_onPrimaryContainer = Color(0xFF97f7b8)
val md_theme_dark_secondary = Color(0xFFb6ccb9)
val md_theme_dark_onSecondary = Color(0xFF213527)
val md_theme_dark_secondaryContainer = Color(0xFF384b3d)
val md_theme_dark_onSecondaryContainer = Color(0xFFd2e8d5)
val md_theme_dark_tertiary = Color(0xFFa2cdda)
val md_theme_dark_onTertiary = Color(0xFF023640)
val md_theme_dark_tertiaryContainer = Color(0xFF214c57)
val md_theme_dark_onTertiaryContainer = Color(0xFFbfeaf7)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1a)
val md_theme_dark_onBackground = Color(0xFFe1e3de)
val md_theme_dark_surface = Color(0xFF191c1a)
val md_theme_dark_onSurface = Color(0xFFfbfdf7)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c9c0)
val md_theme_dark_outline = Color(0xFF8b938b)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1a)
val md_theme_dark_inverseSurface = Color(0xFFe1e3de)

// val seed = Color(0xFF51a471)
// val error = Color(0xFFba1b1b)
